[package]
name    = "blott"
version = "0.1.0"
authors = ["Alex Mitchell <alex@alexthemitchell.com>"]

[dependencies]
base64      = "0.6.0"
clap        = "2.26.0"
egg-mode    = "0.10.0"
markdown    = "0.2.0"
regex       = "0.2.2"
rust-s3     = "0.7.0"
seahash     = "3.0.5"
time        = "0.1"
